/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'outline-variant': '#c0c8cd',
        'on-secondary-fixed-variant': '#3a485b',
        'surface-dim': '#d2d9f4',
        'primary-fixed': '#c0e8ff',
        'surface-variant': '#dae2fd',
        'surface-container-high': '#e2e7ff',
        'on-tertiary-fixed-variant': '#005323',
        'on-background': '#131b2e',
        'secondary-fixed': '#d5e3fc',
        'outline': '#70787d',
        'on-tertiary-container': '#82e595',
        'primary-fixed-dim': '#92cfee',
        'on-secondary-fixed': '#0d1c2e',
        'surface-container-lowest': '#ffffff',
        'tertiary-container': '#00672d',
        'on-tertiary-fixed': '#00210a',
        'on-surface': '#131b2e',
        'inverse-on-surface': '#eef0ff',
        'on-primary-container': '#9bd7f7',
        'secondary-container': '#d5e3fc',
        'on-secondary-container': '#57657a',
        'inverse-primary': '#92cfee',
        'error': '#ba1a1a',
        'on-error-container': '#93000a',
        'on-primary': '#ffffff',
        'primary': '#00475e',
        'error-container': '#ffdad6',
        'surface-tint': '#236580',
        'primary-container': '#1a5f7a',
        'on-primary-fixed-variant': '#004d66',
        'background': '#faf8ff',
        'surface-container': '#eaedff',
        'surface-container-low': '#f2f3ff',
        'on-error': '#ffffff',
        'on-surface-variant': '#40484d',
        'surface-bright': '#faf8ff',
        'tertiary-fixed': '#95f8a7',
        'on-secondary': '#ffffff',
        'inverse-surface': '#283044',
        'secondary-fixed-dim': '#b9c7df',
        'tertiary-fixed-dim': '#79db8d',
        'on-tertiary': '#ffffff',
        'tertiary': '#004c20',
        'on-primary-fixed': '#001e2b',
        'surface-container-highest': '#dae2fd',
        'secondary': '#515f74',
        'surface': '#faf8ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'card-padding': '1.25rem',
        'touch-hero': '4.5rem',
        'stack-gap-sm': '0.75rem',
        'gutter-compact': '1rem',
        'margin-screen': '1rem',
        'touch-min': '3.5rem',
        'stack-gap-lg': '2rem',
        'gutter-spacious': '1.5rem',
        'stack-gap-md': '1.25rem',
      },
      fontFamily: {
        sans: ['var(--font-public-sans)', 'Public Sans', 'system-ui', 'sans-serif'],
        'label-action': ['var(--font-public-sans)', 'Public Sans'],
        'headline-md': ['var(--font-public-sans)', 'Public Sans'],
        'display-lg': ['var(--font-public-sans)', 'Public Sans'],
        'body-md': ['var(--font-public-sans)', 'Public Sans'],
        'queue-token-mobile': ['var(--font-public-sans)', 'Public Sans'],
        'display-lg-mobile': ['var(--font-public-sans)', 'Public Sans'],
        'label-supporting': ['var(--font-public-sans)', 'Public Sans'],
        'body-lg': ['var(--font-public-sans)', 'Public Sans'],
        'queue-token': ['var(--font-public-sans)', 'Public Sans'],
        'headline-lg': ['var(--font-public-sans)', 'Public Sans'],
      },
      fontSize: {
        'label-action': ['20px', { lineHeight: '26px', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'display-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'queue-token-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-lg-mobile': ['26px', { lineHeight: '34px', fontWeight: '700' }],
        'label-supporting': ['15px', { lineHeight: '20px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'queue-token': ['44px', { lineHeight: '52px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
